apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: onzack-cluster-monitoring
spec:
  groups:
  - name: common
    rules:
    - record: instance:kube_node_role
      expr: kube_node_role * on(node) group_left(instance) label_replace(node_uname_info, "node", "$1", "nodename", "(.*)")
  - name: cpu
    rules:
    - record: instance:node_cpu_seconds_total:sum_rate
      expr: sum(rate(node_cpu_seconds_total{mode!="idle"}[5m])) by (cpu,instance)
    - record: kube_node_status_allocatable:cpu:sum
      expr: sum by (node) (kube_node_status_allocatable{resource="cpu"})
    - record: kube_node_status_allocatable:cpu:avg
      expr: avg by (node) (kube_node_status_allocatable{resource="cpu"})
  - name: memory
    rules:
    - record: instance:node_memory_MemUsed_bytes:sum
      expr: sum(node_memory_MemTotal_bytes{job="node-exporter"}) by (instance) - sum(node_memory_MemAvailable_bytes{job="node-exporter"}) by (instance)
    - record: kube_node_status_allocatable:memory:sum
      expr: sum by (node) (kube_node_status_allocatable{resource="memory"})
    - record: kube_node_status_allocatable:memory:avg
      expr: avg by (node) (kube_node_status_allocatable{resource="memory"})
  - name: storage
    rules:
    - record: instance:node_disk_read_bytes_total:sum_rate
      expr: sum(rate(node_disk_read_bytes_total[5m])) by (instance)
    - record: instance:node_disk_reads_completed_total:sum_rate
      expr: sum(rate(node_disk_reads_completed_total[5m])) by (instance)
    - record: instance:node_disk_read_time_seconds_total:sum_rate
      expr: sum(rate(node_disk_read_time_seconds_total[5m])) by (instance)
    - record: instance:node_disk_written_bytes_total:sum_rate
      expr: sum(rate(node_disk_written_bytes_total[5m])) by (instance)
    - record: instance:node_disk_writes_completed_total:sum_rate
      expr: sum(rate(node_disk_writes_completed_total[5m])) by (instance)
    - record: instance:node_disk_write_time_seconds_total:sum_rate
      expr: sum(rate(node_disk_write_time_seconds_total[5m])) by (instance)
  - name: network
    rules:
    - record: instance:node_network_receive_bytes_total:sum_rate
      expr: sum(rate(node_network_receive_bytes_total[5m])) by (instance)
    - record: instance:node_network_receive_packets_total:sum_rate
      expr: sum(rate(node_network_receive_packets_total[5m])) by (instance)
    - record: instance:node_network_receive_drop_total:sum_rate
      expr: sum(rate(node_network_receive_drop_total[5m])) by (instance)
    - record: instance:node_network_transmit_bytes_total:sum_rate
      expr: sum(rate(node_network_transmit_bytes_total[5m])) by (instance)
    - record: instance:node_network_transmit_packets_total:sum_rate
      expr: sum(rate(node_network_transmit_packets_total[5m])) by (instance)
    - record: instance:node_network_transmit_drop_total:sum_rate
      expr: sum(rate(node_network_transmit_drop_total[5m])) by (instance)
